"""update orders financial fields

Revision ID: 1fc87e66b656
Revises: fee14fc4ce97
Create Date: 2026-03-11 17:29:48.634379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc87e66b656'
down_revision: Union[str, None] = 'fee14fc4ce97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('partner_delivery', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('platform_order_commission', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('courier_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('platform_delivery_commission', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('restaurant_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'orders', 'couriers', ['courier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'restaurant_amount')
    op.drop_column('orders', 'platform_delivery_commission')
    op.drop_column('orders', 'courier_amount')
    op.drop_column('orders', 'platform_order_commission')
    op.drop_column('orders', 'courier_id')
    op.drop_column('orders', 'partner_delivery')
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
