"""add stripe fields

Revision ID: 95ee824f518c
Revises: 1fc87e66b656
Create Date: 2026-03-11 19:20:08.919434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ee824f518c'
down_revision: Union[str, None] = '1fc87e66b656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('couriers', sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=False))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('stripe_charge_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('transfer_group', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('transfer_status', sa.String(length=50), nullable=False))
    op.add_column('restaurants', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'stripe_onboarding_complete')
    op.drop_column('restaurants', 'stripe_account_id')
    op.drop_column('orders', 'transfer_status')
    op.drop_column('orders', 'transfer_group')
    op.drop_column('orders', 'stripe_charge_id')
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('couriers', 'stripe_onboarding_complete')
    op.drop_column('couriers', 'stripe_account_id')
    # ### end Alembic commands ###
